[build]
public_url = "./"
minify = "on_release"

[serve]
addresses = ["0.0.0.0"]

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
    "@tailwindcss/cli",
    "-i",
    "./resources/style.css",
    "-o",
    "./resources/tailwind.css",
]

[[proxy]]
backend = "https://wynnmap.zatzou.com/api/"

[[proxy]]
backend = "wss://wynnmap.zatzou.com/api/v1/territories/ws"
ws = true
